### ISSUE TITLE
Define an image preprocessing protocole

### ISSUE THREAD

**Issue by afduquebr** [DiegoHerrera262/Correlation-Techniques-for-Face-Recognition#11]
The main idea of this task is to generate a protocole that allows the improvement of the algorithm that correlates the data base acquired and the sample. 

- [ ] Finding a Matlab function that normalizes the bright, contrast and light from each image according to the background and color skin.

**Comment by DiegoHerrera262** [comment]
Try Using High pass filter for edge enhancement. Use function **EnhanceBorder.m**. It simply asks for the image to be enhanced (not necessarily in grayscale), and the radius of the filter in the frequency domain. I tried this myself, and highlighted my eyes, some features of my nose and my lips. Perhaps combination of this technique with some other process could help
