### ISSUE TITLE
Assess pertinence of image normalization

### ISSUE THREAD

**Issue by DiegoHerrera262** [DiegoHerrera262/Correlation-Techniques-for-Face-Recognition#9]

**Comment by DiegoHerrera262** [comment]
<img width="1653" alt="Captura de Pantalla 2020-05-22 a la(s) 11 55 27 a  m" src="https://user-images.githubusercontent.com/59120315/82692139-c53bae80-9c24-11ea-8233-81d6ce5113de.png">
<img width="1653" alt="Captura de Pantalla 2020-05-22 a la(s) 11 53 58 a  m" src="https://user-images.githubusercontent.com/59120315/82692150-ca98f900-9c24-11ea-9f0c-dd3c28bc52e2.png">

The normalization still does not make the filter intensity-robust. Some other type of preprocessing might be needed. Some preprocessing that enhances facial features (:( obviously). Also, the database used up to this point must be changed, the face must be cropped without any background component.

**Comment by DiegoHerrera262** [comment]
It is necessary to address this issue quite urgently. Please look up documentation on this techniques. Usually the main sources are papers, but try to find tutorials and books.

**Comment by afduquebr** [comment]
Ok, I am going to search for info based on our needs.

**Comment by DiegoHerrera262** [comment]
Included adding zeros to the frequencies along the axes in function **EnhanceBorder.m**. Also used a High Pass Filter for edge enhancement, but this procedure is not tested yet.

**Comment by DiegoHerrera262** [comment]
Tested image processing using PSE and Peak location. Used image 1 on database as reference for computing a 1-sample MACE filter. The correlation output and PSE metric were computed for all the images in the training dataset using the MACE computed thusly.

## Testing No Preprocessing

<img width="1120" alt="Captura de Pantalla 2020-06-02 a la(s) 10 24 44 p  m" src="https://user-images.githubusercontent.com/59120315/83593035-6a0d9400-a521-11ea-972d-793e6d1fc542.png">

Peak is clear and defined for sample 12. However, it is not clear if this means that the sample is appropriate, since until now, there has not been implemented a test using impostor class images. Clearly both images are quite similar. Worst performance is sample 4, and also, the peak is not centered as in the other cases. I assume that the nature of the peak depends a lot on the intensity. This technique does not allow for image registering with this sample, for the peaks, in most of the cases, are already centered. 

**NOTE:** It is important to take datasets that correspond to good illumination and in which the relevant features, like eyes and nose, be quite resolved. Perhaps implementing the code on my smartphone (better camera), might produce better results.

# Testing Laplace filtering

Laplace filter is used for edge enhancement. The built-in function ```locallapfilt(image, sigma, alpha)``` implements convolution with a Laplace filter. The results are shown bellow. Values used ```alpha = 0.5; sigma = 0.4;```

<img width="1120" alt="Captura de Pantalla 2020-06-02 a la(s) 10 16 06 p  m" src="https://user-images.githubusercontent.com/59120315/83593548-9fff4800-a522-11ea-9889-f2843d2299eb.png">

The PCE was reduced as the edges are sharpened. Perhaps considering that the intensity at defined borders is reduced, this might be due to feature enhancement. There seems to be some correlation between non-centered images and poor PCE. The differences in the metric for the test training images is reduced. Still comparison with impostor class images is necessary for assessment of the filter. Here image registration seems more possible.

# Testing High Pass Filter

Used a radius of 5 for the frequency-domain filter. The processing was carried out with the function ```EnhanceBorder```. The results are shown bellow.

<img width="1120" alt="Captura de Pantalla 2020-06-02 a la(s) 10 21 13 p  m" src="https://user-images.githubusercontent.com/59120315/83594014-b2c64c80-a523-11ea-9056-845cd0d2bbf2.png">

The value of the PCE is further reduced, perhaps due to the huge extraction of edges. Plus, the difference in the metric for the test training images is diminished. The location of the peaks is quite different, so the image registration is imperative.

# Conclusion

It is absolutely important to acquire a dataset with excellent illumination conditions, and preprocess them in order to extract relevant facial features. This will allow the metric to perform better image registration. Also, comparison with impostor class images is necessary so that we can see if the filter is able to distinguish a face or not.
